# Generated by Django 5.2.4 on 2025-07-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock',
        ),
    ]
