# Generated by Django 5.2.4 on 2025-07-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookauthor_unique_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
