# Generated by Django 5.2.4 on 2025-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_bookauthor_id_alter_bookgenre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
